
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author waels
 */
package javaapplication1;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Sign_Up extends javax.swing.JFrame {

    /**
     * Creates new form Sign_Up
     */
    public Sign_Up() {
        super("Sign UP");
        initComponents();
        random();
    }
    public void random() {
        Random rd = new Random();
        int randomNum = rd.nextInt(1000);
        adid.setText("" + randomNum);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        account = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        un = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        fn = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        cpwd = new javax.swing.JPasswordField();
        create = new javax.swing.JButton();
        back = new javax.swing.JButton();
        qust = new javax.swing.JComboBox<>();
        sqa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        account.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "New Account", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 36), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        fname.setName("fname"); // NOI18N
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        un.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        un.setText("Username");

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });

        fn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fn.setText("First Name");

        cp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cp.setText("Confirm password");

        a.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        a.setText("Age");

        ln.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ln.setText("Last Name");

        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });

        cpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpwdActionPerformed(evt);
            }
        });

        create.setIcon(new javax.swing.ImageIcon("C:\\Users\\waels\\Downloads\\plus.png")); // NOI18N
        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\waels\\Downloads\\logout.png")); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        qust.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a security question :", "What is your favorite book/movie/TV show?", "In what city were you born?", "What is the name of your first pet?" }));

        sqa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Security Question");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Awnser");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Admin_ID");

        adid.setEditable(false);
        adid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account);
        account.setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountLayout.createSequentialGroup()
                        .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(a)
                                    .addComponent(un)
                                    .addComponent(fn)
                                    .addComponent(ln)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(accountLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cp)))
                        .addGap(42, 42, 42)
                        .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sqa)
                            .addComponent(age)
                            .addComponent(uname)
                            .addComponent(fname)
                            .addComponent(lname)
                            .addComponent(qust, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwd)
                            .addComponent(cpwd)
                            .addComponent(adid)))
                    .addGroup(accountLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(back)
                        .addGap(35, 35, 35)
                        .addComponent(create)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fn))
                .addGap(18, 18, 18)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ln))
                .addGap(18, 18, 18)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(un)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a))
                .addGap(18, 18, 18)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cp))
                .addGap(42, 42, 42)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(create))
                .addGap(37, 37, 37))
        );

        fname.getAccessibleContext().setAccessibleName("nameAccount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(510, 663));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
setVisible(false);
Login ob=new Login();
ob.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your  code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        boolean test;
        if (fname.getText().length() < 3){
            JOptionPane.showMessageDialog(null, "First name must be at least 3 characters long!", "Error", JOptionPane.ERROR_MESSAGE);
            test=false;
    }
        else if (lname.getText().length() < 3){
            JOptionPane.showMessageDialog(null, "Last name must be at least 3 characters long!", "Error", JOptionPane.ERROR_MESSAGE);
            test=false;
    }
        else if (uname.getText().length() < 3){
            JOptionPane.showMessageDialog(null, "Username must be at least 3 characters long!", "Error", JOptionPane.ERROR_MESSAGE);
            test=false;
    }
        else if ((Integer.parseInt(age.getText()) < 10) || age.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Age must be at least 10!", "Error", JOptionPane.ERROR_MESSAGE);
            test=false;
    }
        else if(((String) qust.getSelectedItem()).equals("Choose a security question :")){
            JOptionPane.showMessageDialog(null, "You have to choose a security question !", "Error", JOptionPane.ERROR_MESSAGE);
            test=false;
        }
        else if (sqa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "put your awnser please !!", "Error", JOptionPane.ERROR_MESSAGE);
            test=false;
        }
        else if (pwd.getText().length() < 4){
            JOptionPane.showMessageDialog(null, "Password must be at least 4 characters long!", "Error", JOptionPane.ERROR_MESSAGE);
            test=false;
    }
        else if (!pwd.getText().equals(cpwd.getText())){
              JOptionPane.showMessageDialog(null, "Confirm password must match password.", "Error", JOptionPane.ERROR_MESSAGE);
              test=false;
         }
        else {
             JOptionPane.showMessageDialog(null, "All fields are valid.", "Success", JOptionPane.INFORMATION_MESSAGE);
             test=true;
         }
        if (test==true){
            try {
                Connection con =JavaApplication1.mycon();
                PreparedStatement ps = con.prepareStatement("INSERT into utilisateur VALUES (?,?,?,?,?,?,?,?)");
                ps.setString(1, adid.getText());
                ps.setString(2, fname.getText());
                ps.setString(3, lname.getText());
                ps.setString(4, uname.getText());
                ps.setString(5, age.getText());
                ps.setString(6, (String) qust.getSelectedItem());
                ps.setString(7, sqa.getText());
                ps.setString(8, pwd.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "New account created", "Success", JOptionPane.INFORMATION_MESSAGE);
                ps.close();
                setVisible(false);
                Login ob=new Login();
                ob.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Sign_Up.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_createActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void cpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpwdActionPerformed

    private void sqaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqaActionPerformed

    private void adidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JPanel account;
    private javax.swing.JTextField adid;
    private javax.swing.JTextField age;
    private javax.swing.JButton back;
    private javax.swing.JLabel cp;
    private javax.swing.JPasswordField cpwd;
    private javax.swing.JButton create;
    private javax.swing.JLabel fn;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel ln;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JComboBox<String> qust;
    private javax.swing.JTextField sqa;
    private javax.swing.JLabel un;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
